import React, { useState } from 'react';
import { ArrowRight, MapPin, Bell, Cpu, Download, X } from 'lucide-react';
import { useUrbanPulse } from '../context/UrbanPulseContext';
import { GISMap } from '../components/map/GISMap';
import { EdgeCameraPanels } from '../components/camera/EdgeCameraPanels';

const value = n => Number.isFinite(n) ? n.toFixed(1) : '—';
const isRoad = e => e.eventType === 'ROAD_OBSERVATION';
function download(events) {
  const rows = events.map(e => ({ event_id:e.id, event_type:e.eventType, timestamp:e.timestamp,
    bus_id:e.busId, camera_id:e.cameraId, latitude:e.lat, longitude:e.lng, gps_source:e.gpsSource,
    confidence:e.confidence, vehicle_count:e.vehicleCount, status:e.status, metadata:e.metadata }));
  const url=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));
  const a=document.createElement('a');a.href=url;a.download='urbanpulse-events.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Metric({label,amount,detail}) {
  return <div className="rounded-xl bg-white border border-slate-200 p-4 shadow-subtle"><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-extrabold text-slate-900 mt-2">{amount}</p><p className="text-xs text-slate-500 mt-1">{detail}</p></div>;
}
function Pipeline({kind,state,connected}) {
  const current=connected && state?.status==='running';
  return <section className="bg-white rounded-xl border border-slate-200 p-5 space-y-3">
    <div className="flex justify-between gap-3"><h2 className="font-bold text-slate-900">{kind==='road'?'Road defect detection':'Traffic congestion indicator'}</h2><span className={current?'text-emerald-700 text-sm':'text-amber-700 text-sm'}>{connected ? state?.status || 'starting' : 'offline'}</span></div>
    <p className="text-sm text-slate-600">{kind==='road'?'YOLO detects supported road defects. Important observations become geospatial events.':'YOLO detects vehicles. A sustained vehicle-count rule estimates congestion in the camera view.'}</p>
    {state?.error && <p role="alert" className="text-sm text-red-700 break-words">{state.error}</p>}
    <div className="flex flex-wrap gap-5 text-sm"><span>Inference <b>{current?value(state?.inference_ms):'—'} ms</b></span><span>Processed <b>{current?value(state?.processed_fps):'—'} FPS</b></span><span>Device <b>{state?.device || '—'}</b></span></div>
    {kind==='traffic' ? <div className="flex flex-wrap gap-4 text-sm"><span>Vehicles now: <b>{current?state?.vehicle_count ?? '—':'—'}</b></span><span>Indicator: <b>{current?state?.congestion_level || 'UNKNOWN':'UNKNOWN'}</b></span><span>Window average: <b>{current?value(state?.average_vehicle_count):'—'}</b></span></div> : <p className="text-sm text-slate-600">Loaded classes: {Object.values(state?.classes || {}).join(', ') || 'Waiting for model'}. Depth is not measured.</p>}
    <p className="text-xs text-slate-500 break-all">{state?.model || 'Model not yet reported'}</p>
  </section>;
}
export function CoreWorkspace({page='dashboard'}) {
  const {detections,edgeStatus,edgeConnected,centralConnection,setActiveRoute,setSelectedReport,setIsNotificationOpen,setActiveFilter}=useUrbanPulse();
  const [query,setQuery]=useState('');const [limit,setLimit]=useState(25);
  const roads=detections.filter(isRoad),traffic=detections.filter(e=>e.eventType==='TRAFFIC_CONGESTION');
  const source=page==='road-intel'?roads:page==='traffic-intel'?traffic:detections;
  const filtered=source.filter(e=>`${e.title} ${e.busId} ${e.id}`.toLowerCase().includes(query.toLowerCase()));
  const headings={dashboard:['Urban intelligence overview','Road observations and congestion events from local inference.'],
    'road-intel':['Road intelligence','Supported defects, model evidence and geospatial reports.'],
    'traffic-intel':['Traffic intelligence','Observed vehicle counts and sustained congestion indicators.'],
    'all-logs':['Event reports','Review and export the events received by the central backend.'],
    'live-city':['GIS event map','Geographic event locations and concentration. GPS source is shown on every event.'],
    'edge-network':['Edge processing','Two independent inference workers on this laptop; important events are buffered locally.'],
    'live-camera':['Inference evidence','Optional annotated previews of the independent model inputs.']};
  const [heading,subtitle]=headings[page] || headings.dashboard;
  const status=edgeStatus?.cameras || {};
  const eventTable=<section className="bg-white rounded-xl border border-slate-200 overflow-hidden">
    <div className="p-4 flex flex-wrap gap-3 items-center justify-between border-b border-slate-100"><h2 className="font-bold">{page==='dashboard'?'Latest events':'Received events'} <span className="text-slate-500 font-normal">({source.length})</span></h2><input aria-label="Search events" placeholder="Search event or bus ID" value={query} onChange={e=>{setQuery(e.target.value);setLimit(25);}} className="border border-slate-200 rounded-lg p-2 text-sm" /></div>
    {!filtered.length ? <div className="p-8 text-center text-slate-500 text-sm">{centralConnection!=='connected'?'Central backend is unavailable. Previously received events remain visible when available.':'No matching model events. Allow a qualifying detection to synchronize; no sample alerts are generated.'}</div> : <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-slate-50 text-slate-500"><tr>{['Observation','Detected at','Source','Location','Status',''].map((label,i)=><th className="px-4 py-3 font-medium" key={i}>{label}</th>)}</tr></thead><tbody>{filtered.slice(0,page==='dashboard'?6:limit).map(e=><tr key={e.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><p className="font-semibold text-slate-900">{e.title}</p><p className="text-xs text-slate-500">{isRoad(e)?(Number.isFinite(e.confidence)?`${Math.round(e.confidence*100)}% detector confidence`:'Confidence unavailable'):`${e.congestionLevel || '—'} · ${e.vehicleCount ?? '—'} vehicles`}</p></td><td className="px-4 py-3 whitespace-nowrap">{new Date(e.timestamp).toLocaleString()}</td><td className="px-4 py-3"><p>{e.busId}</p><p className="text-xs text-slate-500">{e.cameraId}</p></td><td className="px-4 py-3"><p>{e.lat?.toFixed(5)}, {e.lng?.toFixed(5)}</p><p className="text-xs text-amber-700">{e.gpsSource}</p></td><td className="px-4 py-3 text-xs">{e.status}</td><td className="px-4 py-3"><button onClick={()=>setSelectedReport(e)} className="text-blue-700 font-semibold whitespace-nowrap">Review →</button></td></tr>)}</tbody></table></div>}
    {page!=='dashboard' && filtered.length>limit && <button onClick={()=>setLimit(n=>n+25)} className="m-4 text-sm text-blue-700">Show 25 more</button>}
  </section>;
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">{heading}</h1><p className="text-sm text-slate-500 mt-1">{subtitle}</p></div><button onClick={()=>download(source)} disabled={!source.length} className="flex gap-2 items-center border border-slate-200 bg-white px-3 py-2 rounded-lg text-sm text-slate-700 disabled:opacity-40"><Download size={16}/>Export events</button></div>
    {page==='dashboard' && <><div className="grid grid-cols-2 xl:grid-cols-4 gap-4"><Metric label="Road reports" amount={roads.length} detail="Stored observations · not surveyed defect count"/><Metric label="Congestion reports" amount={traffic.length} detail="Stored qualifying count-based events"/><Metric label="Edge workers" amount={edgeConnected?`${Object.values(status).filter(s=>s.status==='running').length}/2`:'Offline'} detail="Actual worker status"/><Metric label="Unsent events" amount={edgeConnected?edgeStatus?.outbox?.pending_events ?? '—':'—'} detail="Local persistent outbox"/></div><div className="grid lg:grid-cols-2 gap-4"><Pipeline kind="road" state={status.road} connected={edgeConnected}/><Pipeline kind="traffic" state={status.traffic} connected={edgeConnected}/></div><div className="flex flex-wrap gap-3"><button onClick={()=>{setActiveFilter('ALL');setActiveRoute('live-city');}} className="rounded-lg bg-blue-600 text-white px-4 py-2 text-sm font-semibold flex items-center gap-2"><MapPin size={16}/>Open GIS map</button><button onClick={()=>setIsNotificationOpen(true)} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold flex items-center gap-2"><Bell size={16}/>Notifications</button><button onClick={()=>setActiveRoute('edge-network')} className="text-sm text-blue-700 px-2 flex items-center gap-2">Inspect edge status <ArrowRight size={16}/></button></div></>}
    {['road-intel','traffic-intel'].includes(page) && <Pipeline kind={page==='road-intel'?'road':'traffic'} state={page==='road-intel'?status.road:status.traffic} connected={edgeConnected}/>}
    {page==='traffic-intel' && <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">This is a count-based congestion indicator, not a trained congestion classifier or measured road speed. A busy free-flowing scene can also contain many vehicles.</p>}
    {['dashboard','road-intel','traffic-intel','all-logs'].includes(page) && eventTable}
    {page==='live-city' && <GISMap height="min(760px, calc(100vh - 240px))"/>}
    {page==='live-camera' && <EdgeCameraPanels/>}
    {page==='edge-network' && <><div className="grid lg:grid-cols-2 gap-4"><Pipeline kind="road" state={status.road} connected={edgeConnected}/><Pipeline kind="traffic" state={status.traffic} connected={edgeConnected}/></div><section className="rounded-xl bg-white border p-5 space-y-3"><h2 className="font-bold flex gap-2 items-center"><Cpu size={18}/>Event synchronization</h2><p className="text-sm">Central backend: <b>{centralConnection}</b> · Pending locally: <b>{edgeConnected?edgeStatus?.outbox?.pending_events ?? '—':'—'}</b></p><p className="text-sm">Last acknowledged sync: {edgeStatus?.outbox?.last_sync?new Date(edgeStatus.outbox.last_sync*1000).toLocaleString():'Not yet reported'}</p>{edgeStatus?.outbox?.error && <p className="text-sm text-amber-800">Sync unavailable: {edgeStatus.outbox.error}</p>}<p className="text-sm">GPS: {edgeStatus?.gps?.valid?`${edgeStatus.gps.source} · ${edgeStatus.gps.latitude.toFixed(5)}, ${edgeStatus.gps.longitude.toFixed(5)}`:'Unavailable; geolocated events paused'}</p><p className="text-sm text-slate-500">Offline check: stop only the central service, wait for a qualifying new event to enter the queue, then restart it. Existing cooldowns may suppress a repeated condition.</p></section><details className="rounded-xl border bg-white p-4 text-sm"><summary className="cursor-pointer font-semibold">Prototype scope</summary><p className="mt-3 text-slate-600">Implemented scope: supported road defects, vehicle detection and tracking, count-based congestion events, event cooldowns, outbox retries, notifications and GIS. GPS is simulated for recorded inputs. Both services run on one laptop. Depth measurement, ANPR, hit-and-run, speeding and moving-camera violations are not demonstrated.</p></details></>}
  </div>;
}

export function CoreReport() {
  const {selectedReport:e,setSelectedReport,updateReportStatus}=useUrbanPulse();
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  if (!e) return null;
  async function review(){setBusy(true);setError('');try{const saved=await updateReportStatus(e.id,'VERIFIED','Reviewed in UrbanPulse prototype');if(!saved)setError('Review could not be saved. Check the central backend.');}catch{setError('Review failed. Try again when the backend is available.');}finally{setBusy(false);}}
  return <div className="fixed inset-0 bg-slate-950/50 z-50 p-4 flex items-center justify-center" role="dialog" aria-modal="true" aria-label="Event evidence"><section className="bg-white rounded-xl max-w-3xl w-full max-h-[90vh] overflow-auto shadow-xl"><div className="p-5 border-b flex justify-between gap-4"><div><h2 className="font-bold text-lg">{e.title}</h2><p className="text-xs text-slate-500 break-all">{e.id}</p></div><button aria-label="Close report" onClick={()=>{setError('');setSelectedReport(null);}}><X/></button></div><div className="p-5 space-y-4">{e.evidenceImg?<img src={e.evidenceImg} alt="Model evidence for this event" className="w-full max-h-80 object-contain rounded-lg bg-slate-950"/>:<p className="p-5 rounded-lg bg-slate-50 text-slate-500 text-sm">No evidence image was attached.</p>}<dl className="grid sm:grid-cols-2 gap-4 text-sm">{[['Timestamp',e.timestamp],['Bus / camera',`${e.busId} / ${e.cameraId}`],['Coordinates',`${e.lat}, ${e.lng}`],['GPS source',e.gpsSource],['Status',e.status],['Detector confidence',Number.isFinite(e.confidence)?`${Math.round(e.confidence*100)}%`:'Not a calibrated probability'],['Model',e.metadata?.model || '—'],['Vehicle count',e.vehicleCount ?? 'Not applicable']].map(([label,val])=><div key={label}><dt className="text-slate-500">{label}</dt><dd className="font-medium break-words">{val}</dd></div>)}</dl><p className="text-sm text-slate-600">{isRoad(e)?'Detection region only; no depth or physical severity measurement.':'Congestion estimated from observed vehicle counts; no speed or traffic-flow measurement.'}</p><div className="flex gap-3 flex-wrap"><button onClick={()=>download([e])} className="border rounded-lg px-3 py-2 text-sm">Export JSON</button>{e.status==='DETECTED' && <button disabled={busy} onClick={review} className="bg-blue-600 text-white rounded-lg px-3 py-2 text-sm disabled:opacity-50">{busy?'Saving…':'Mark reviewed'}</button>}</div>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<details className="text-sm"><summary className="cursor-pointer text-blue-700">Detection and rule metadata</summary><pre className="mt-2 rounded bg-slate-50 p-3 text-xs overflow-auto">{JSON.stringify(e.metadata,null,2)}</pre></details></div></section></div>;
}
